# Example configuration file for prometheus-openstack-exporter
# Copyright (C) 2016-2019 Canonical, Ltd.
#

listen_port: VAR_LISTEN_PORT # listenPort=9183
cache_refresh_interval: VAR_CACHE_REFRESH_INTERVAL # cacheRefreshInterval=300 In seconds
cache_file: VAR_CACHE_FILE # cacheFileName=$(mktemp -p /dev/shm/)
cloud: VAR_CLOUD # cloud=${OS_REGION_NAME:-mycloud}
openstack_allocation_ratio_vcpu: VAR_VCPU_RATIO # vcpuRatio=1.0
openstack_allocation_ratio_ram: VAR_RAM_RATIO # ramRatio=1.0
openstack_allocation_ratio_disk: VAR_DISK_RATIO # diskRatio=1.0

# Configure the enabled collectors here.  Note that the Swift account
# collector in particular has special requirements.
enabled_collectors: # enabledCollectors=cinder neutron nova
  - VAR_ENABLED_COLLECTORS

# To export hypervisor_schedulable_instances metric set desired instance size
schedulable_instance_size:
    ram_mbs: VAR_SCHEDULABLE_INSTANCE_RAM # schedulableInstanceRam=4096
    vcpu: VAR_SCHEDULABLE_INSTANCE_VCPU # schedulableInstanceVcpu=2
    disk_gbs: VAR_SCHEDULABLE_INSTANCE_DISK # schedulableInstanceDisk=20

# Uncomment if the cloud doesn't provide cinder / nova volumes:
use_nova_volumes: VAR_USE_NOVA_VOLUMES # useNovaVolumes=True
